report_mail:
  mail_to: dev-team <dev@theplant.jp>, emergency <emergency@theplant.jp>
  mail_from: dev3-monitor <monitor@theplant.jp>

monitors:
  DiskfullMonitor:
    disks: /dev/mapper/VolGroup00-LogVol00
    threshold: 85

  BackupMonitor:
    dir: /home/asics/backups