report_mail:
  mail_to: michael <michael@theplant.jp>, hlxwell <hlxwell@gmail.com>
  mail_from: test-monitor <monitor@theplant.jp>

monitors:
  DiskfullMonitor:
    disks: /dev/disk0s2, /dev/disk0s3
    threshold: 5
    onduty_time_start: 9
    onduty_time_end: 18
    offduty_threshold: 98

  BackupMonitor:
    dir: /Users/hlxwell