report_mail:
  mail_to: dev-team <dev@theplant.jp>, emergency <emergency@theplant.jp>
  mail_from: joblet-monitor <monitor@theplant.jp>

monitors:
  DiskfullMonitor:
    disks: /
    threshold: 85
    onduty_time_start: 9
    onduty_time_end: 18
    offduty_threshold: 98