report_mail:
  mail_to: dev-team <michael@theplant.jp>
  mail_from: dev2-monitor <monitor@theplant.jp>

monitors:
  DiskfullMonitor:
    disks: /dev/mapper/VolGroup00-LogVol00
    threshold: 80

  BackupMonitor:
    dir: /home/asics/backups