report_mail:
  mail_to: dev-team <michael@theplant.jp>
  mail_from: test-monitor <monitor@theplant.jp>

monitors:
  DiskfullMonitor:
    disks: /dev/disk0s2,/dev/disk0s3
    threshold: 50

  BackupMonitor:
    dir: /Users/hlxwell